### ISSUE TITLE
Verification Error

### ISSUE THREAD

**Issue by yk-sgr** [Rubicon-Bot/RubiCon#101]
### Issue Type
- [x] Bug.
- [ ] Feature.

### Report
VerificationListener.java:84 -> Nullpointerexception

**Comment by yk-sgr** [comment]
I can't reproduce this. 🤔

**Comment by leonkappes** [comment]
Closed: Error was that the DevBot is missing something in DB looks like my DB is corrupted

**Comment by yk-sgr** [comment]
It's not a bug in your bot. The error was thrown by the main bot.

**Comment by leonkappes** [comment]
Hmm I thought it because my DB is buggy

**Comment by DRSchlaubi** [comment]
Can't reproduce tested setup at 2 times and it works

**Comment by DRSchlaubi** [comment]
Only happens when you're using a dev version from Rubicon
