### ISSUE TITLE
Readd bio to profile command

### ISSUE THREAD

**Issue by yk-sgr** [Rubicon-Bot/RubiCon#70]
This feature was mistakenly removed in this [Commit](https://github.com/Rubicon-Bot/Rubicon/commit/10bec4d1fbe4d72648fb8609f0b3b3e66ea5ba3a)

**Comment by leonkappes** [comment]
Es ist [2e66b29](https://github.com/Rubicon-Bot/Rubicon/commit/2e66b298d9e3144294c4eb2546d9d801ca867219) gefixt worden.
