### ISSUE TITLE
Mute HierarchyException

### ISSUE THREAD

**Issue by leonkappes** [Rubicon-Bot/RubiCon#74]
### Issue Type
- [x] Bug.
- [ ] Feature.

#### Description

Mute command tries to create Mute role but own role is not high enough

### Steps to reproduce

>Leave Blank if this is a Feature Request

- Step 1
  - execute the Mute command when the Rubicon role isn't high enough
- Step 2
  - see the error

**Comment by leonkappes** [comment]
Will be fixed with the Weekly Saturday patch on 2/3/2018

**Comment by DRSchlaubi** [comment]
fixed in #80
