### ISSUE TITLE
Blacklist Rework

### ISSUE THREAD

**Issue by leonkappes** [Rubicon-Bot/RubiCon#76]
### Issue Type
- [ ] Feature.

- [x] Bug.

#### Description

You can whitelist a channel to make Commands there if one is set the bot only answers there if no one set I will answer everywhere

### Steps to reproduce

>Leave Blank if this is a Feature Request

- Step 1
  - neumachen

**Comment by DRSchlaubi** [comment]
werde mich heute dransetzen

**Comment by DRSchlaubi** [comment]
Added in #135
