### ISSUE TITLE
verification kick

### ISSUE THREAD

**Issue by leonkappes** [Rubicon-Bot/RubiCon#78]
### Issue Type
- [x] Bug.
- [ ] Feature.

#### Description

When the Bot goes offline until a User got kicked he will never get Kicked

### Steps to reproduce

>Leave Blank if this is a Feature Request

- Step 1
  - Stop Bot
- Step 2
  - Kick won't work after restart

**Comment by DRSchlaubi** [comment]
Fix WIP 80% done will be finished soon
