### ISSUE TITLE
Maintenance Command

### ISSUE THREAD

**Issue by yk-sgr** [Rubicon-Bot/RubiCon#81]
### Issue Type
- [ ] Bug.
- [x] Feature.

### Description
- Botowner Command

`rc!maintenance <time> <text>`

Sets the bots playing status to <time> + <text>and plays a funny maintenance announcement sound in all voice channels with which the bot ist connected. The command could also enable a mode that only botowner can execute commands.

**Comment by leonkappes** [comment]
jo würd des gerne amchen wenn kein andere will

**Comment by yk-sgr** [comment]
Yes. Do that.
