### ISSUE TITLE
automatic issue generation 

### ISSUE THREAD

**Issue by DRSchlaubi** [Rubicon-Bot/RubiCon#84]
### Issue Type
- [ ] Bug.
- [x] Feature.

#### Description

Automatic issue generation through `rc!bug` and `rc!feedback` command

**Comment by yk-sgr** [comment]
Should we use a lib or HttpRequest?

**Comment by leonkappes** [comment]
take lib request is too much

**Comment by yk-sgr** [comment]
I think too

**Comment by yk-sgr** [comment]
I will let this first up to grab. I don't know if I have time at the weekend to implement this too.
