### ISSUE TITLE
Toggleable LevelUp Message

### ISSUE THREAD

**Issue by yk-sgr** [Rubicon-Bot/RubiCon#85]
### Issue Type
- [ ] Bug.
- [x] Feature.

#### Description

Make the LevelUp message toggleable because it's on some servers pretty annoying.

Default: enabled

**Comment by DRSchlaubi** [comment]
@LeeDJD will add that

**Comment by leonkappes** [comment]
Of course, I do.

**Comment by leonkappes** [comment]
Finished in #89 and will be added to Main on weekly build at Saturday
