### ISSUE TITLE
Extensive log

### ISSUE THREAD

**Issue by leonkappes** [Rubicon-Bot/RubiCon#88]
### Issue Type
- [ ] Bug.
- [x] Feature.

#### Description

At rc!log , there should be an option to activate Role Updates etc. // By beta#0922

### Steps to reproduce

>Leave Blank if this is a Feature Request

- Step 1
  - Sample Step
- Step 2
  - another sample Step
- Step 4
  - Feel free to add Steps

**Comment by yk-sgr** [comment]
I will try to do this at the weekend.
