### ISSUE TITLE
rc!serverinfo <Guildid>

### ISSUE THREAD

**Issue by lucsoft** [Rubicon-Bot/RubiCon#95]
### Issue Type
- [ ] Bug
- [x] Feature.

#### Description

mit rc!serverinfo <Guildinfo> -- Guildinfos über ein bestimmten server

**Comment by DRSchlaubi** [comment]
I think it's useless cause I would only work for servers which has invited rubicon

**Comment by yk-sgr** [comment]
Yes, but we can check if the server exists in our db
